language: java
sudo: required
jdk:
 - oraclejdk8

before_install:
 - chmod +x mvnw
 - sudo apt-get install jq
 - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

after_success:
 - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r target/site/jacoco/jacoco.xml

install:
 - cd back && mvn clean install -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_TOKEN
  app: viandasya	

git:
  depth: 25
  quiet: true
dist: trusty
